### ISSUE TITLE
Unknown option "width" for grid-item-card

### ISSUE THREAD

**Issue by Legrandin** [executablebooks/sphinx-design#109]
### Describe the bug

I am using a `grid-item-card` like this:

```
.. grid-item-card::
    :width: auto

   Some text
```

but I get the message from sphinx:

```ERROR in "grid-item-card" directive: unknown option: "width".```

While in theory `width` should be supported: https://sphinx-design.readthedocs.io/en/latest/cards.html#card-options .

### Reproduce the bug

See above for sample.

### List your environment

This happens with:
```
Sphinx==5.3.0
sphinx_design==0.3.0
docutils==0.19
```

**Comment by jpmckinney** [comment]
Similarly, I get `Directive 'grid-item-card': Unknown option: class-img-top`

**Comment by Legrandin** [comment]
Thanks! Any chance for a release to be published on PyPI soon?

**Comment by tkknight** [comment]
I believe I also have the same issue:

`ERROR: Error in "grid-item-card" directive: unknown option: "class-img-top"`

...which I think the docs state should be supported, so +1 for getting https://github.com/executablebooks/sphinx-design/pull/115 merged.
