### ISSUE TITLE
i18n: Spurious (and translatable) alt-text added to cards

### ISSUE THREAD

**Issue by jpmckinney** [executablebooks/sphinx-design#111]
### Describe the bug

Due to lines like:

https://github.com/executablebooks/sphinx-design/blob/42077cf08756019db3936fbd9a66d68f6ce6d23d/sphinx_design/cards.py#L117

My POT file contains, in this case:

```
msgid "card-img-top"
msgstr ""
```

### Reproduce the bug

Run `sphinx-build -b gettext docs _build` (or whatever paths are appropriate) while using this package and using the `img-background`, `img-top` or `img-bottom` options.

### List your environment

Not environment dependent.

**Comment by chrisjsewell** [comment]
I believe this was closed in #114
