### ISSUE TITLE
Sphinx-design stylesheet is not added to the document head

### ISSUE THREAD

**Issue by K20shores** [executablebooks/sphinx-design#116]
### Describe the bug

**context**
When I added sphinx-design to my docs and built the site, I saw that sphinx-design classes and HTML layouts are applied to the page, but I the css styles are not loaded.

**expectation**
I expected styles to load.

**bug**
When I inspect the stylesheets loaded in the documents `head`, I don't see any reference to a style sheet made by sphinx design (which I think is of the form `design-style.hash.min`. That stylesheet is located in `_build/html/_sphinx_design_static`, but there is no reference to this in  the document header.

**problem**
This is a problem for people using sphinx-doc because sphinx-doc does not add any value when it's stylesheet is not added.

This occurs with Python 3.9.15 and these versions of installed sphinx packages

### Reproduce the bug

You can reproduce this on a branch in my repository. Note that in `docs/source/index.rst` there are some directives to create a grid.

```
git clone https://github.com/NCAR/tuv-x.git                                 
cd tuv-x                                                                    
git checkout 208-write-a-contributors-document                              
conda create --name env                                                     
conda activate env                                                          
cd docs                                                                     
conda install --file requirements.txt --name env -y                         
conda install sphinx-design                                                 
git clone https://github.com/VACUMM/sphinx-fortran.git                      
cd sphinx-fortran                                                           
pip install .                                                               
cd ../                                                                      
make html                                                                   
open _build/html/index.html 
```

After inspecting the head of that page, you will not find the style file.

### List your environment

Package  | Version | Source
------------- | --------------- | -------- 
pydata-sphinx-theme   |     0.8.1    |           pyhd8ed1ab_0    conda-forge
sphinx               |      4.5.0          |     pyh6c4a22f_0    conda-forge
sphinx-book-theme      |    0.3.3          |     pyhd8ed1ab_0    conda-forge
sphinx-design      |        0.3.0      |         pyhd8ed1ab_0    conda-forge
sphinx-fortran      |       1.1.1         |            pypi_0    pypi
sphinxcontrib-applehelp  |  1.0.2   |                    py_0    conda-forge
sphinxcontrib-devhelp   |   1.0.2   |                    py_0    conda-forge
sphinxcontrib-htmlhelp  |   2.0.0     |          pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath    |   1.0.1      |                 py_0    conda-forge
sphinxcontrib-qthelp    |   1.0.3          |             py_0    conda-forge
sphinxcontrib-serializinghtml  |1.1.5      |         pyhd8ed1ab_2    conda-forge

**Comment by chrisjsewell** [comment]
You haven't added it to the extensions list

**Comment by K20shores** [comment]
> You haven't added it to the extensions list

Perhaps you looked at a commit where I had briefly removed it. But, that is not the case, especially since the html structure generated by sphinx-design was added as could be seen in the inspector. At any rate, [this draft PR has the extention](https://github.com/NCAR/tuv-x/pull/230/files#diff-008dcb3426febd767787b1521f1fe33086313b927ea37eaab86df5fa88a51698R38) but you can [see in the preview of the docs](https://ncar.github.io/tuv-x/branch/208-write-a-contributors-document/) that the style is not applied. If you inspect any of the large picture on the homepage, you will see that they are in fact in sphinx-design grids, but have no styling because the style document is not linked.

**Comment by chrisjsewell** [comment]
Heya, yeh I'm not sure why this is added: https://github.com/NCAR/tuv-x/blob/1a2e9b86054f418397f24f32a2e24d59572d0fa4/docs/source/conf.py#L79-L82

but this is not the way to add custom css, as you are overriding sphinx's internal logic, its with https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_css_files

**Comment by K20shores** [comment]
Oh, thank you for catching that. That fixes the issue.
