### ISSUE TITLE
support sphinx 6

### ISSUE THREAD

**Issue by nicoa** [executablebooks/sphinx-design#118]
### Context

Some packages are relying on this one to be installed and the pinned dependencies (i.e. the testing pipelines in https://github.com/pydata/pydata-sphinx-theme/pull/1097 ) and it would be nice to have version 6 and up.

Please let me know on your opinion wether simply loosening the restriction is fine or additional tests are required.

**Comment by zerocewl** [comment]
any news?

**Comment by nicoa** [comment]
Hey @zerocewl , I'm not familiar with this package and got no response on
> Please let me know on your opinion wether simply loosening the restriction is fine or additional tests are required.

As there are quite a few votings for this issue, I may put together a quick PR the next days and will see what the maintainers of this repo say.

**Comment by zerocewl** [comment]
@nicoa 

I'm not sure if there is any active maintainer?!?

A PR would be nice, but would it contain any more then the already (not merged) PR #106?

**Comment by chrisjsewell** [comment]
> New myst-parser is released, which will let us test on Sphinx 6 here.

working on it 😉 https://github.com/executablebooks/MyST-Parser/commits/master

**Comment by nicoa** [comment]
I guess there are ;-) yes, that PR is actively worked on apparently, you can monitor that one, thanks for pointing out!

**Comment by zerocewl** [comment]
bump

**Comment by bastimeyer** [comment]
> working on it

With the MyST-Parser 0.19.0 release that has added support for Sphinx 6, is there a chance for an update and new release here as well?
https://github.com/executablebooks/MyST-Parser/releases/tag/v0.19.0

Thank you very much!

**Comment by dbitouze** [comment]
As a `MyST-Parser` and `sphinx-design` user, I strongly support this FR!

**Comment by Giddius** [comment]
As far as my docs are concerned, just force installing sphinx 6 after installing sphinx-design and then building, did not break anything.

Windows 10-64
Python 3.11

**Comment by bastimeyer** [comment]
Apparently there was an attempt made to move/update to `sphinx-design2` in #123 by @chrisjsewell, but the updated project now lives here:
https://github.com/sphinx-extensions2/sphinx-design2

According to its readme, it's "a fork for local development", but it's still published to PyPI:
https://pypi.org/project/sphinx-design2/

However, the readme of the `sphinx-extensions2` GH orga suggests that this is indeed the new location for the project:
https://github.com/sphinx-extensions2

Why the fork if repos can just be moved, with a convenient redirection being added by GitHub on the old location? Why the new PyPI package? The `sphinx-design2` readme also contains stuff from the old project.

Is `sphinx-design2` actually considered stable and available for public use, @chrisjsewell? It does contain the necessary changes for sphinx 6.

**Comment by danieljanes** [comment]
@choldgraf, what's your perspective on the comment from @bastimeyer?

It would be great to understand which PyPI package (`sphinx_design` or `sphinx-design2`) is more actively maintained to decide which package we should depend on.
