### ISSUE TITLE
Support Sphinx 7

### ISSUE THREAD

**Issue by demberto** [executablebooks/sphinx-design#130]
### Context

*No context required*

**Comment by danieljanes** [comment]
This blocks us from upgrading to Sphinx 7

**Comment by RobPasMue** [comment]
This is also blocking us from updating to Sphinx 7 on multiple repos. Could we get #131 approved and merged, together with a new release? =)

**Comment by AA-Turner** [comment]
Likely resolved by #148!

A

**Comment by chrisjsewell** [comment]
all done 👍
