### ISSUE TITLE
Custom code block names

### ISSUE THREAD

**Issue by thephez** [executablebooks/sphinx-design#154]
### Context

I recently used a documentation tool that allowed assigning custom names to tabbed code blocks. For example, something like this would result in 2 tabs - one named "JavaScript" and one named "Node.js":

\```javascript JavaScript
     some js code
\```
\```javascript Node.js
      some js code
\```

This was a useful feature at times and would be nice to have in this (already very nice) extension. If I"m reading the docs correctly, it's already possible to name non-code block tabs, but I don't think that's true for code blocks.

### Proposal

Adding a label/name option for code within a `tab-set-code` block and probably syncing based on that instead of the `language` attribute.

**Comment by agoose77** [comment]
Exactly this ^

Thanks both, hopefully this resolves things?

**Comment by thephez** [comment]
Thanks @redeboer and @agoose77 ! :raised_hands: Exactly what I needed. I was hung up on some syntactical thing as usual. :man_facepalming:
