### ISSUE TITLE
tab-item with replacement directive

### ISSUE THREAD

**Issue by zerothi** [executablebooks/sphinx-design#155]
### Describe the bug

**context**
I have an rst replacement text:

```rst
.. |pip| replace:: pip
```
I then have a tab with this:

```rst
.. tab-set::
    .. tab-item:: |pip|
<more tabs etc.>
```

**expectation**
I expected `|pip|` to be replaced correctly (note this works with other tab systems, `inline-tabs` e.g.

**bug**

It now shows the tab name as:
```
<substitution_reference refname=”pip”>pip</substitution_reference>
```

**problem**
This is a problem for people because it might be necessary to *globally* control some of the tab names.
Say OS's, terminals etc.

### Reproduce the bug

Context above should give enough instructions. Rather simple IMHO.
If you need more details, please let me know!

**Comment by chrisjsewell** [comment]
fixed with #135
