### ISSUE TITLE
Support latest Octicon icons

### ISSUE THREAD

**Issue by MarcSkovMadsen** [executablebooks/sphinx-design#180]
### Context

I am trying to do docs contributions to [HoloViz Panel](https://panel.holoviz.org/index.html). I notice that something does not work when I use specific Octicon icons in the cards.

In https://github.com/holoviz/panel/issues/6318 I request Panel to support these icons. But I'm told its really Sphinx-Design that do not support them. Sphinx-Design only supports the octicon-icons listed in https://sphinx-design.readthedocs.io/en/latest/badges_buttons.html#octicon-icons

### Proposal

Support all Octicon Icons that can be found at https://primer.style/foundations/icons

### Not Working

![image](https://github.com/executablebooks/sphinx-design/assets/42288570/3a8885d1-d1b0-4915-843d-449aed66675f)

**Comment by chrisjsewell** [comment]
This should be closed by #171, but feel free to re-open if not

**Comment by MarcSkovMadsen** [comment]
Thx
