### ISSUE TITLE
Sphinx 8 compatibility

### ISSUE THREAD

**Issue by sigma67** [executablebooks/sphinx-design#206]
### Describe the bug

**context**
When I update Sphinx to Sphinx 8, `sphinx-design` is causing a locking failure.

**expectation**
I expected the lock to succeed.

**bug**
Resolution fails

**problem**
Issue is `sphinx<8` in the pyproject.toml of this project.

### Reproduce the bug

Try to install Sphinx 8 and sphinx-design in the same venv

**Comment by chrisjsewell** [comment]
done in #212
