### ISSUE TITLE
Non-default "outline" doesn't work, at least in article-info

### ISSUE THREAD

**Issue by pradyunsg** [executablebooks/sphinx-design#24]
### Describe the problem

Setting outlines with the knobs provided on article-info don't work. This likely affects other parts of the code as well, but this is the only one I've tried so far. The following is despite setting `muted` as the outline:

<img width="353" alt="Screenshot 2021-08-15 at 23 20 58" src="https://user-images.githubusercontent.com/3275593/129494387-f31b8c4c-44fc-4f1b-a637-d6f93aa27e13.png">

### Steps to reproduce

Try with the code block:

````
```{article-info}
:avatar: https://avatars.githubusercontent.com/u/3275593?s=80&v=4
:avatar-link: https://pradyunsg.me
:avatar-outline: muted
:author: Pradyun Gedam
:date: Aug 15, 2021
:read-time: 5 min read
```
````

Notice that the avatar outline is, in fact, not muted.

### The version of Python you're using

N/A

### Your operating system

N/A

### Versions of your packages

Latest Firefox (91.0)
Latest Chrome (92.0)
Current `main` for sphinx-design: 6930a00b48c80d4b772261ed66d342dc90c612f3

Other pieces are N/A, as far as I can tell.

### Additional context

These properties should likely not be called "outline". They're setting the [border](https://developer.mozilla.org/en-US/docs/Web/CSS/border), which is a separate thing (at least in CSS) from [outline](https://developer.mozilla.org/en-US/docs/Web/CSS/outline).

**Comment by pradyunsg** [comment]
This also affects https://sphinx-design.readthedocs.io/en/latest/additional.html#article-info, but is less noticable due to the background on the image.

`border-color: var(--sd-color-muted) !important;` is overriden by the `border` declaration on the next line.

**Comment by chrisjsewell** [comment]
yep that looks like the one cheers

> These properties should likely not be called "outline". They're setting the border,

Note both bootstrap and material-ui have "outline" variants of components which set border properties, e.g.

- https://getbootstrap.com/docs/5.0/components/buttons/#outline-buttons
- https://material-ui.com/components/buttons/#outlined-buttons

this is where I have taken the term outline from
