### ISSUE TITLE
Is there a plan to add material design inline icons?

### ISSUE THREAD

**Issue by 2bndy5** [executablebooks/sphinx-design#36]
I thought I'd ask this here since you're moving away from sphinx-panels - this is looking great BTW!

I see that there are inline icons for FontAwesome and Octicon. I'm helping develop a port of mkdocs-material theme to sphinx, and our docs could use the set of inline icons from the material design set.

## For reference
1. This is the theme I'm helping: Its called [sphinx-immaterial](https://github.com/jbms/sphinx-immaterial) because there was a previous (kind of a "hobbyist" attempt) called sphinx-material. 
2. This is the [set of icons supported by all the material design docs themes](https://github.com/squidfunk/mkdocs-material/tree/master/material/.icons/material) (in svg form)

---
ps - If you're curious to see the sphinx-immaterial theme in action, it is [hosted on gh-pages](https://jbms.github.io/sphinx-immaterial/index.html). I've also made sure it works rather well with RTD builds 😉 .

**Comment by 2bndy5** [comment]
# Success

I managed to get this working! I had to update the json from the google/material-icons repo's latest commit (some icons seem to have been added since the last release; these new icons show on the [material design site's list of material icons](https://fonts.google.com/icons), but they aren't included in the latest release assets 😕.

Here's a screenshot of the new roles being used in the sphinx-immaterial theme's docs
![image](https://user-images.githubusercontent.com/14963867/141596584-1246a44c-58c1-47a1-a64d-8c77b514c1c1.png)

They also work seemlessly (without extra css from the theme's docs' build config) in the light theme
![image](https://user-images.githubusercontent.com/14963867/141596850-a9fe45b6-e84a-45db-a07c-7121ceaada5a.png)


PR coming shortly.

**Comment by chrisjsewell** [comment]
awesome 😄
