### ISSUE TITLE
Font Awesome Icons are not working

### ISSUE THREAD

**Issue by damienrj** [executablebooks/sphinx-design#38]
### Describe the problem

![image](https://user-images.githubusercontent.com/2729283/139295782-79411ac3-3e50-408c-ad0e-1eaab94d496c.png)
The example showing how to use github icons is not working locally or on the doc site https://sphinx-design.readthedocs.io/en/furo-theme/badges_buttons.html?highlight=icons#inline-icons for the furo theme.

### Steps to reproduce

https://sphinx-design.readthedocs.io/en/furo-theme/badges_buttons.html?highlight=icons#inline-icons

**Comment by 2bndy5** [comment]
+1 for this. It still fails when using 6.0.0beta2 (latest) min.css. Additionally, [there is something rendering for the RTD CI on my PR, but it doesn't look right](https://sphinx-design--41.org.readthedocs.build/en/41/badges_buttons.html#fontawesome-icons).

I noticed that different themes of the sphinx-design docs rendered differently (with respect 2 the `fa*` roles), but they all seem to show something incorrect. So, I pushed forward and tried the icons in the sphinx-immaterial theme (using 6.0.0beta2), and it does work. However, the size is unaffected despite whatever I put in the `fa*` role's args.

```rst
        - :fab:`git;2em` ``fontawesome/brands/git``
        - :fab:`git-alt;2em` ``fontawesome/brands/git-alt``
        - :fab:`git-square;2em` ``fontawesome/brands/git-square``
        - :fab:`github;2em` ``fontawesome/brands/github``
        - :fab:`github-alt;2em` ``fontawesome/brands/github-alt``
        - :fab:`github-square;2em` ``fontawesome/brands/github-square``
        - :fab:`gitlab;2em` ``fontawesome/brands/gitlab``
        - :fab:`gitkraken;2em` ``fontawesome/brands/gitkraken``
        - :fab:`bitbucket;2em` ``fontawesome/brands/bitbucket``
```
renders like
![image](https://user-images.githubusercontent.com/14963867/141648216-4a32facc-3228-4ac7-ad7b-e981a89f4c02.png)

**Comment by chrisjsewell** [comment]
Yeh cheers I'll try to look into it soonish. Really that's why I prefer the octicon icons and soon #41, since here the svg's are directly packaged and so it's easier to ensure consistency

**Comment by pradyunsg** [comment]
The problem here might be that sphinx-design isn't adding the html_css_files for any theme other than alabaster. :)

https://github.com/executablebooks/sphinx-design/blob/2cdadca8b1bf97a20edcd531b5db08342722322f/docs/conf.py#L17-L20

**Comment by chrisjsewell** [comment]
That looks like the one cheers! 😅

**Comment by 2bndy5** [comment]
Using latest docs with alabaster theme:
![image](https://user-images.githubusercontent.com/14963867/168165819-1d247a1d-3f76-4cfc-a9f6-de0b6076fed5.png)

Probably should note that this is rendered in Firefox.

**Comment by pradyunsg** [comment]
Ah, then there's possibly a more foundational issue here. :)

**Comment by 2bndy5** [comment]
might be a breaking change in the FA CSS. I added the `font-family` property to the `.fas` rule and I get the icon to show in the Alabaster theme
```css
.fa, .fab, .fad, .fal, .far, .fas {
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
  display: inline-block;
  font-style: normal;
  font-variant: normal;
  text-rendering: auto;
  line-height: 1;
  font-family: 'FontAwesome'; /* this property was missing */
}
```
But the coloring also seems like an undesirable effect.
```md
An icon {fas}`spinner;sd-bg-primary sd-bg-text-primary`, some more text.
```
rendered
![image](https://user-images.githubusercontent.com/14963867/168172477-32dc0675-dcf7-4ead-8974-72b5e85ccf3e.png)

**Comment by pradyunsg** [comment]
Alternatively, adding a `fa` class to the generated element also works. :)

**Comment by 2bndy5** [comment]
@pradyunsg I found this comment
https://github.com/executablebooks/sphinx-design/blob/43bb2cc28f936c8d3483bd7b1077d56293ebe5db/sphinx_design/icons.py#L27-L29

I'm not sure if there is a newer implication since the latest FA release is v6.1.1. Nonetheless, I think `fa` class should be added to all FA roles for better backward compatibility.
