### ISSUE TITLE
Clickable cards not possible with grid-item-card in rst

### ISSUE THREAD

**Issue by mluerig** [executablebooks/sphinx-design#47]
### Describe the problem

unless I have missed something, it appears that cards can't be made clickable through the grid-item-card directive (except the first one) 

### Steps to reproduce

this works:

    .. grid:: 2
    
	    .. grid-item::
    
		    .. card::  example 1
			    :link: example1.html
    
			    first example
		    
	    .. grid-item::
    
		    .. card::  example 2
			    :link: example2.html
    
			    second example

this doesn't:

    .. grid:: 2
    
        .. grid-item-card::  example 1
		    :link: example1.html
    
            first example
    
        .. grid-item-card::  example 2
		    :link: example2.html
    
            second example

### The version of Python you're using

3.7

### Your operating system

win10

### Versions of your packages

     pip freeze

AddGrain==8
adjust==1
alabaster==0.7.12
appdirs==1.4.4
argh==0.26.2
argon2-cffi==21.1.0
arrow==0.13.1
astroid @ file:///C:/ci/astroid_1625075983732/work
async-generator==1.10
atomicwrites==1.4.0
attrs @ file:///tmp/build/80754af9/attrs_1620827162558/work
autopep8 @ file:///tmp/build/80754af9/autopep8_1615918855173/work
AWarpSharp2==4
Babel @ file:///tmp/build/80754af9/babel_1620871417480/work
backcall @ file:///home/ktietz/src/ci/backcall_1611930011877/work
bcrypt @ file:///C:/ci/bcrypt_1597918112552/work
beautifulsoup4==4.10.0
Bilateral==3
BilateralGPU==6
binaryornot @ file:///tmp/build/80754af9/binaryornot_1617751525010/work
black==19.10b0
bleach @ file:///tmp/build/80754af9/bleach_1626470256873/work
BM3D==8
brotlipy==0.7.0
certifi==2021.5.30
cffi @ file:///C:/ci/cffi_1625831764494/work
chardet @ file:///C:/ci/chardet_1607706910910/work
click @ file:///tmp/build/80754af9/click_1621604852318/work
cloudpickle @ file:///tmp/build/80754af9/cloudpickle_1598884132938/work
colorama @ file:///tmp/build/80754af9/colorama_1607707115595/work
commonmark==0.9.1
cookiecutter @ file:///tmp/build/80754af9/cookiecutter_1617748928239/work
cryptography @ file:///C:/ci/cryptography_1616769432139/work
CTMF==5
cycler==0.10.0
DCTFilter==2
Deblock==6
decorator @ file:///tmp/build/80754af9/decorator_1621259047763/work
defusedxml @ file:///tmp/build/80754af9/defusedxml_1615228127516/work
Descale==7
DFTTest==7
diff-match-patch @ file:///tmp/build/80754af9/diff-match-patch_1594828741838/work
docopt==0.6.2
docutils @ file:///C:/ci/docutils_1620828194019/work
edi-rpow2==29
EEDI2==7
EEDI3m==4
entrypoints==0.3
FFmpegSource2==2.40
FFT3DFilter==1
FFTW3-Library==3.3.5
flake8 @ file:///tmp/build/80754af9/flake8_1615834841867/work
FluxSmooth==2
fmtconv==27
furo==2021.11.16
future==0.18.2
fvsfunc==0+2f5b28d
havsfunc==0+98997de
HQDn3D==2.0.1
idna @ file:///home/linux1/recipes/ci/idna_1610986105248/work
imageio==2.9.0
imagesize @ file:///home/ktietz/src/ci/imagesize_1611921604382/work
importlib-metadata @ file:///C:/ci/importlib-metadata_1617877486026/work
inflection==0.5.1
intervaltree @ file:///tmp/build/80754af9/intervaltree_1598376443606/work
ipykernel @ file:///C:/ci/ipykernel_1596208728219/work/dist/ipykernel-5.3.4-py3-none-any.whl
ipython @ file:///C:/ci/ipython_1617121109687/work
ipython-genutils @ file:///tmp/build/80754af9/ipython_genutils_1606773439826/work
ipywidgets==7.6.5
isort @ file:///tmp/build/80754af9/isort_1625834821980/work
jedi @ file:///C:/ci/jedi_1606932641827/work
Jinja2 @ file:///tmp/build/80754af9/jinja2_1612213139570/work
jinja2-time @ file:///tmp/build/80754af9/jinja2-time_1617751524098/work
jsonschema @ file:///tmp/build/80754af9/jsonschema_1602607155483/work
jupyter==1.0.0
jupyter-client @ file:///tmp/build/80754af9/jupyter_client_1616770841739/work
jupyter-console==6.4.0
jupyter-core @ file:///C:/ci/jupyter_core_1612213516947/work
jupyterlab-pygments @ file:///tmp/build/80754af9/jupyterlab_pygments_1601490720602/work
jupyterlab-widgets==1.0.2
keyring @ file:///C:/ci/keyring_1621524751168/work
kiwisolver==1.3.1
KNLMeansCL==1.1.1
lazy-object-proxy @ file:///C:/ci/lazy-object-proxy_1616529290879/work
m2r==0.2.1
MarkupSafe @ file:///C:/ci/markupsafe_1594405949945/work
matplotlib==3.4.2
mccabe==0.6.1
Median==4
mistune @ file:///C:/ci/mistune_1594373272338/work
muvsfunc==0+8ba1436
mvsfunc==0+b9218ff
MVTools==23
mypy-extensions==0.4.3
nbclient @ file:///tmp/build/80754af9/nbclient_1614364831625/work
nbconvert @ file:///C:/ci/nbconvert_1624479160228/work
nbformat @ file:///tmp/build/80754af9/nbformat_1617383369282/work
nbsphinx==0.8.7
nest-asyncio @ file:///tmp/build/80754af9/nest-asyncio_1613680548246/work
networkx==2.6.2
NNEDI3==12
nnedi3-resample==0+8fff075
nnedi3-rpow2==6
NNEDI3-Weights==1
NNEDI3CL==8
notebook==6.4.6
numpy==1.18.5
numpydoc @ file:///tmp/build/80754af9/numpydoc_1605117425582/work
opencv-contrib-python==3.4.9.33
packaging @ file:///tmp/build/80754af9/packaging_1625611678980/work
pandas==1.1.2
pandocfilters @ file:///C:/ci/pandocfilters_1605102427207/work
paramiko @ file:///tmp/build/80754af9/paramiko_1598886428689/work
parso==0.7.0
pathspec==0.7.0
pexpect @ file:///tmp/build/80754af9/pexpect_1605563209008/work
pickleshare @ file:///tmp/build/80754af9/pickleshare_1606932040724/work
Pillow==8.3.1
pkginfo==1.8.1
pluggy @ file:///C:/ci/pluggy_1615976530170/work
poyo @ file:///tmp/build/80754af9/poyo_1617751526755/work
prometheus-client==0.12.0
prompt-toolkit @ file:///tmp/build/80754af9/prompt-toolkit_1616415428029/work
psutil @ file:///C:/ci/psutil_1612298033174/work
ptyprocess @ file:///tmp/build/80754af9/ptyprocess_1609355006118/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pycodestyle @ file:///home/ktietz/src/ci_mi/pycodestyle_1612807597675/work
pycparser @ file:///tmp/build/80754af9/pycparser_1594388511720/work
pydocstyle @ file:///tmp/build/80754af9/pydocstyle_1621600989141/work
pyflakes @ file:///home/ktietz/src/ci_ipy2/pyflakes_1612551159640/work
Pygments @ file:///tmp/build/80754af9/pygments_1621606182707/work
pykwalify==1.8.0
pylint @ file:///C:/ci/pylint_1625467870548/work
pyls-black @ file:///tmp/build/80754af9/pyls-black_1607553132291/work
pyls-spyder @ file:///tmp/build/80754af9/pyls-spyder_1613849700860/work
PyNaCl @ file:///C:/ci/pynacl_1595009241355/work
pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1608057966937/work
pyparsing @ file:///home/linux1/recipes/ci/pyparsing_1610983426697/work
pyradiomics==3.0.1
pyrsistent @ file:///C:/ci/pyrsistent_1600123688363/work
PySocks @ file:///C:/ci/pysocks_1594394709107/work
python-dateutil @ file:///tmp/build/80754af9/python-dateutil_1626374649649/work
python-jsonrpc-server @ file:///tmp/build/80754af9/python-jsonrpc-server_1600278539111/work
python-language-server @ file:///tmp/build/80754af9/python-language-server_1607972495879/work
python-slugify @ file:///tmp/build/80754af9/python-slugify_1620405669636/work
pytz @ file:///tmp/build/80754af9/pytz_1612215392582/work
PyWavelets==1.1.1
pywin32==227
pywin32-ctypes @ file:///C:/ci/pywin32-ctypes_1594392691209/work
pywinpty==1.1.6
PyYAML==5.4.1
pyzmq==20.0.0
QDarkStyle @ file:///tmp/build/80754af9/qdarkstyle_1617386714626/work
qstylizer @ file:///tmp/build/80754af9/qstylizer_1617713584600/work/dist/qstylizer-0.1.10-py2.py3-none-any.whl
QtAwesome @ file:///tmp/build/80754af9/qtawesome_1615991616277/work
qtconsole @ file:///tmp/build/80754af9/qtconsole_1623278325812/work
QtPy==1.9.0
readme-renderer==30.0
recommonmark==0.7.1
regex @ file:///C:/ci/regex_1625610189850/work
requests @ file:///tmp/build/80754af9/requests_1608241421344/work
requests-toolbelt==0.9.1
rfc3986==1.5.0
rope @ file:///tmp/build/80754af9/rope_1623703006312/work
Rtree @ file:///C:/ci/rtree_1618421019532/work
ruamel.yaml==0.16.12
ruamel.yaml.clib==0.2.6
SangNom==42
scikit-image==0.18.2
scipy==1.7.0
Send2Trash==1.8.0
SimpleITK==2.0.2
six @ file:///tmp/build/80754af9/six_1623709665295/work
snowballstemmer @ file:///tmp/build/80754af9/snowballstemmer_1611258885636/work
sortedcontainers @ file:///tmp/build/80754af9/sortedcontainers_1623949099177/work
soupsieve==2.3.1
Sphinx @ file:///tmp/build/80754af9/sphinx_1623884544367/work
sphinx-bootstrap-theme==0.8.0
sphinx-design==0.0.13
sphinx-multibuild==1.2.1
sphinxcontrib-applehelp @ file:///home/ktietz/src/ci/sphinxcontrib-applehelp_1611920841464/work
sphinxcontrib-devhelp @ file:///home/ktietz/src/ci/sphinxcontrib-devhelp_1611920923094/work
sphinxcontrib-htmlhelp @ file:///tmp/build/80754af9/sphinxcontrib-htmlhelp_1623945626792/work
sphinxcontrib-jsmath @ file:///home/ktietz/src/ci/sphinxcontrib-jsmath_1611920942228/work
sphinxcontrib-qthelp @ file:///home/ktietz/src/ci/sphinxcontrib-qthelp_1611921055322/work
sphinxcontrib-serializinghtml @ file:///tmp/build/80754af9/sphinxcontrib-serializinghtml_1624451540180/work
spyder @ file:///C:/ci/spyder_1626182175529/work
spyder-kernels @ file:///C:/ci/spyder-kernels_1625671145829/work
TCanny==12
terminado==0.12.1
testpath @ file:///tmp/build/80754af9/testpath_1624638946665/work
text-unidecode==1.3
textdistance @ file:///tmp/build/80754af9/textdistance_1612461398012/work
three-merge @ file:///tmp/build/80754af9/three-merge_1607553261110/work
tifffile==2021.7.2
tinycss @ file:///tmp/build/80754af9/tinycss_1617713798712/work
toml @ file:///tmp/build/80754af9/toml_1616166611790/work
tornado @ file:///C:/ci/tornado_1606935947090/work
tqdm==4.61.2
traitlets @ file:///home/ktietz/src/ci/traitlets_1611929699868/work
TTempSmooth==3
twine==3.6.0
typed-ast @ file:///C:/ci/typed-ast_1624953789477/work
typing-extensions @ file:///tmp/build/80754af9/typing_extensions_1624965014186/work
ujson @ file:///C:/ci/ujson_1611244941645/work
Unidecode @ file:///tmp/build/80754af9/unidecode_1614712377438/work
urllib3 @ file:///tmp/build/80754af9/urllib3_1625084269274/work
VSFilter==4
VSFilterMod==5.2.5
watchdog @ file:///C:/ci/watchdog_1624955113514/work
wcwidth @ file:///tmp/build/80754af9/wcwidth_1593447189090/work
webencodings==0.5.1
whichcraft @ file:///tmp/build/80754af9/whichcraft_1617751293875/work
widgetsnbextension==3.5.2
win-inet-pton @ file:///C:/ci/win_inet_pton_1605306165655/work
wincertstore==0.2
wrapt==1.12.1
Yadifmod==10
yapf @ file:///tmp/build/80754af9/yapf_1615749224965/work
zipp @ file:///tmp/build/80754af9/zipp_1625570634446/work
ZNEDI3==2.1

**Comment by chrisjsewell** [comment]
Heya, I can produce links with RST, see #61 and https://sphinx-design--61.org.readthedocs.build/en/61/other.html

Note I had to change the indentation in your example, which I think may have been at fault:

```restructuredtext
.. grid:: 2

   .. grid-item-card:: example 1
      :link: example1.html

      first example

   .. grid-item-card:: example 2
      :link: example2.html

      second example

```
