### ISSUE TITLE
Better Grids on Mobile

### ISSUE THREAD

**Issue by rmorshea** [executablebooks/sphinx-design#50]
### Description / Summary

The number of columns in a grid is rigidly set which means that when the screen size changes, the view does not react and reduce the number of columns being shown. This tends to lead to ugly or unreadable results. In the sample below, I would expect that, at this width, the grid would have automatically reduced the number of columns down to 1:

<img width="362" alt="image" src="https://user-images.githubusercontent.com/4041990/146984462-6d07e439-5eb4-4403-8bc0-86e450b74cec.png">

### Value / benefit

This would make documentation more readable on mobile devices.

**Comment by chrisjsewell** [comment]
> The number of columns in a grid is rigidly set 

Heya, this is certainly not the case. Have you checked the documentation for how to set adaptive column numbers for the screen-width: https://sphinx-design.readthedocs.io/en/furo-theme/grids.html

**Comment by rmorshea** [comment]
Ah, thanks for pointing that out!

**Comment by chrisjsewell** [comment]
No worries 😄
