### ISSUE TITLE
Can't use sphinx-design with Sphinx 5.0 preview

### ISSUE THREAD

**Issue by lsaffre** [executablebooks/sphinx-design#65]
### Describe the bug

When I have sphinx-design installed, then I can't upgrade to Sphinx 5 preview:

```console
$ pip install -U --pre Sphinx
Requirement already satisfied: Sphinx in /home/luc/virtualenvs/py38/lib/python3.8/site-packages (4.5.0)
Collecting Sphinx
  Using cached Sphinx-5.0.0b1-py3-none-any.whl (3.1 MB)
(...)
sphinx-design 0.1.0 requires sphinx<5,>=3, but you have sphinx 5.0.0b1 which is incompatible.

```
This is a problem for people who want to test the newest Sphinx version.

### Reproduce the bug

$ pip install -U --pre Sphinx

### List your environment

Using Python 3.8.0 under Ubuntu

**Comment by varac** [comment]
[Spinx 5.0.0 got released](https://pypi.org/project/Sphinx/5.0.0/) so this is even more important.

**Comment by pradyunsg** [comment]
Closing since https://github.com/executablebooks/sphinx-design/pull/74 added the support requested in OP. :)
