### ISSUE TITLE
Card links do not have a discernible name (accessibility issue)

### ISSUE THREAD

**Issue by bertiewooster** [executablebooks/sphinx-design#78]
### Describe the bug

**context**
When I use cards on a Sphinx site, with Furo theme

**expectation**
I expected the card link to have a discernible name so people using screen readers can tell what the link leads to

**bug**
But instead the link has no discernible name
Here's the warning from [Lighthouse](https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk)'s accessibility checker:

```
Links do not have a discernible name
Link text (and alternate text for images, when used as links) that is discernible, unique, and focusable improves the navigation experience for screen reader users.
```

**problem**
This is a problem for people using screen readers because they will not be read a name for the link that will help them decide if they should follow the link.

### Reproduce the bug

Here is a [page built using cards](https://output.circle-artifacts.com/output/job/2fcb6c2d-6976-42b1-b915-7e0aad93ba42/artifacts/0/doc/_build/html/index.html). Here is the corresponding [accessibility report from Lighthouse](https://googlechrome.github.io/lighthouse/viewer/?psiurl=https%3A%2F%2Foutput.circle-artifacts.com%2Foutput%2Fjob%2F2fcb6c2d-6976-42b1-b915-7e0aad93ba42%2Fartifacts%2F0%2Fdoc%2F_build%2Fhtml%2Findex.html&strategy=mobile&category=performance&category=accessibility&category=best-practices&category=seo&category=pwa&utm_source=lh-chrome-ext).

### List your environment

```
MyST-parser: latest (0.18.0)
Furo theme: latest (2022.06.21)
Sphinx: 4.5.0
```

**Comment by chrisjsewell** [comment]
> I expected the card link to have a discernible name

Hey @bertiewooster, I'm afraid I don't know exactly what this means.
Card links are simply constructed as regular `nodes.reference` docutils nodes, so it should not act differently to any other sphinx link?

It would perhaps be really helpful, if you could post what the current generated HTML is, for a minimal card example, and what the desired HTML would be?

**Comment by bertiewooster** [comment]
Hi @chrisjsewell, thanks for your response. 

## Current generated HTML
Hopefully this [pre-existing example](https://output.circle-artifacts.com/output/job/9bb30655-e91f-4697-be3a-02655c6616d6/artifacts/0/doc/_build/html/index.html) will clarify the accessibility issue. 

### With a card
The first card link (anchor) is 

`<a class="sd-stretched-link reference internal" href="[install.html#installation](view-source:https://output.circle-artifacts.com/output/job/9bb30655-e91f-4697-be3a-02655c6616d6/artifacts/0/doc/_build/html/install.html#installation)"><span class="std std-ref"></span></a>`

There is no name for the link (link text) indicating the topic of the link: If you were to put this HTML in a web page absent its context, nothing would be presented to the user because there is no text (or image) within the anchor element. Therefore, a screen reader will not be able to speak a useful name to a visitor, so they will now know if they want to follow this link.

### Without a card
Contrast this with the [same link without using cards](https://docs.sympy.org/dev/index.html)

`<a class="reference internal" href="[install.html#installation](view-source:https://docs.sympy.org/dev/install.html#installation)"><span class="std std-ref">Installation</span></a><a class="headerlink" href="[#installation](view-source:https://docs.sympy.org/dev/index.html#installation)" title="Permalink to this heading">#</a>`

where the link text is _Installation_, which a screen reader will speak to the visitor, who can then decide if they want to learn more about installation.

## Desired HTML

### Naive, sub-optimal approach
If the link text _Installation_ were simply added inside the card anchor, it would

- address the accessibility issue, but
- appear twice when viewed on a screen: once for the link text and once for the card.

### Approach which should work for both visual display and screen readers
I found the [recommendation to include `aria-label` and `aria-hidden="true"`](https://stackoverflow.com/questions/26032089/in-html-how-can-i-have-text-that-is-only-accessible-for-screen-readers-i-e-fo#26032207) so for example I believe this HTML would work:

`<a class="sd-stretched-link reference internal" href="[install.html#installation](view-source:https://output.circle-artifacts.com/output/job/9bb30655-e91f-4697-be3a-02655c6616d6/artifacts/0/doc/_build/html/install.html#installation) "aria-label="Installation" aria-hidden="true"><span class="std std-ref"></span></a>`

I checked that making such a modification does not cause _Installation_ to appear twice on a screen. It would be best to verify that a screenreader speaks _Installation_ (as the `aria-label`).

**Comment by chrisjsewell** [comment]
Thanks for the explanation @bertiewooster 😄 I'll see what I can do about achieving this

**Comment by chrisjsewell** [comment]
See #89, for what I felt was the simplest solution. Thoughts welcome?
