### ISSUE TITLE
tab-set-code produces warning for code-block

### ISSUE THREAD

**Issue by tcmetzger** [executablebooks/sphinx-design#79]
### Describe the bug

**context**
When I use `.. code-block::` directives inside of `.. tab-set-code::` 

**expectation**
I expected the docs to build without warning or error.

**bug**
But instead I get a warning when running `make html`: `WARNING: All children of a 'tab-code-set' should be a 'literal_block' [design.tab_code]`

```console
$ make html
```

**problem**
This is a problem because according to the [documentation](https://sphinx-design.readthedocs.io/en/latest/tabs.html#tabbed-code-examples), `.. tab-set-code::` should work with `.. code-block::` directives, and the (apparently unnecessary) warning is confusing.

### Reproduce the bug

In a RST file, include the following:

```
.. tab-set-code::

    .. code-block:: sh

        cd sphinx
```

run `make html`

This gives me the aforementioned warning.

If instead I use:

```
.. tab-set-code::

    .. literalinclude:: ./snippet.py
        :language: python
```

I don't get the warning

### List your environment

sphinx 5.0.2  
pydata-sphinx-theme 0.9.0
sphinx-design 0.2.0
Python 3.10.5
Linux-5.13.0-52-generic-x86_64-with-glibc2.31

**Comment by bryevdv** [comment]
It looks like this is the relevant check:

https://github.com/executablebooks/sphinx-design/blob/a060931933eec842e3ed1b0f4829045151242762/sphinx_design/tabs.py#L143-L150

However, the Sphinx `CodeBlock` directive actually returns a 1-element list with the `literal_block` inside:

https://github.com/sphinx-doc/sphinx/blob/b9736f23484b16feef86208ab00dd947c54446ba/sphinx/directives/code.py#L169

**Comment by tcmetzger** [comment]
Seems like this was actually due to me using an incorrectly escaped character - I'm closing this issue as this seems to work correctly. Apologies!
